//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFly.BeckEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRent
    {
        public int DocId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<decimal> Cost { get; set; }
    }
}
