//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFly.BeckEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationPeriods
    {
        public int DocId { get; set; }
        public string CountryCode { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Flight { get; set; }
        public string Hotel { get; set; }
        public string RideBy { get; set; }
        public decimal ParticipationFee { get; set; }
        public decimal TotalAmountRequested { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
