//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFly.BeckEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int DocId { get; set; }
        public System.DateTime FlightDate { get; set; }
        public string Class { get; set; }
        public decimal Cost { get; set; }
        public string CountryCodeDest { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
