//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFly.BeckEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureReplacement
    {
        public int DocId { get; set; }
        public string CourseName { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan FromHour { get; set; }
        public System.TimeSpan ToHour { get; set; }
        public string CompleteBy { get; set; }
    }
}
