//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFly.BeckEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReckoningDocument
    {
        public int DocId { get; set; }
        public string UserId { get; set; }
        public string ConcentrationExpenses { get; set; }
        public string AccommodationAbroad { get; set; }
        public string StayExpense { get; set; }
        public string CarRent { get; set; }
        public string OtherOxpense { get; set; }
        public string AdvanceGiven { get; set; }
        public decimal AdvanceAmount { get; set; }
        public string SignPresididnt { get; set; }
        public System.DateTime Date { get; set; }
        public string Sign { get; set; }
    
        public virtual User User { get; set; }
    }
}
