//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFlyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Id { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Faculty { get; set; }
        public Nullable<int> Department { get; set; }
        public string Role { get; set; }
        public Nullable<int> PercentageJob { get; set; }
        public string CellNum { get; set; }
        public Nullable<int> ApplicationRole { get; set; }
    
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User11 { get; set; }
        public virtual User User3 { get; set; }
    }
}
